### PR TITLE
[RFR] Change all camelCase classes to hyphens

### PR DESCRIPTION
**Pull request by thiagotomasi**
This PR fix the issue #20

### CODE REVIEW

**Comment by HugoGiraudel** [comment]
Maybe prefix it with `[RFR]` (if it is indeed *Ready For Review*). :)

**Comment by HugoGiraudel** [comment]
If I recall correctly, some mixins and variables also are camelCased.

**Comment by thiagotomasi** [comment]
@HugoGiraudel thanks very much for the tip :wink:
I found some more cases to fix!

**Comment by gakimball** [comment]
Thanks so much! We're going to deploy this as 1.2 today.

**Pull request merged**
