### PR TITLE
[RFR] Improved -mui-build-selector to use a list rather than a string

### LINKED ISSUE #13: Using lists rather than strings when needed
Rather than concatenating strings and commas in order [to form a selector](https://github.com/zurb/motion-ui/blob/master/src/util/_selector.scss), I would advise actually appending to an empty list, then you don't have to deal with separators. Also it's what lists are made for.

### PR DESCRIPTION
**Pull request by HugoGiraudel**
Fix #13.

### CODE REVIEW

**Comment by gakimball** [comment]
This is the output I get for active states:

```scss
.slideInDown.mui-enter, .mui-enter-active {
  -webkit-transform: translateY(0);
      -ms-transform: translateY(0);
          transform: translateY(0); }
```

It should be:

```scss
.slideInDown.mui-enter.mui-enter-active {
  -webkit-transform: translateY(0);
      -ms-transform: translateY(0);
          transform: translateY(0); }
```

**Comment by HugoGiraudel** [comment]
Let me check that.

**Comment by HugoGiraudel** [comment]
Are you 100% sure the previous version was working as expected? I don't see what could be causing this issue from the first glance.

**Comment by HugoGiraudel** [comment]
Found the problem. Will fix.

**Comment by HugoGiraudel** [comment]
Could you please retry?

**Comment by gakimball** [comment]
If you set the `chain` property of `$motion-ui-classes` to `false`, you get this output:

```scss
// Setup class
-mui-enter {
  -webkit-transform: translateY(-100%);
      -ms-transform: translateY(-100%);
          transform: translateY(-100%);
  transition-property: -webkit-transform, opacity;
  transition-property: transform, opacity;
  -webkit-backface-visibility: hidden;
          backface-visibility: hidden; }

// Activate class
-mui-enter-mui-enter-active {
  -webkit-transform: translateY(0);
      -ms-transform: translateY(0);
          transform: translateY(0); }
```

Expected output is:

```scss
// Setup class
.slideIn-mui-enter.slideIn-mui-enter-active {
  -webkit-transform: translateY(-100%);
      -ms-transform: translateY(-100%);
          transform: translateY(-100%);
  transition-property: -webkit-transform, opacity;
  transition-property: transform, opacity;
  -webkit-backface-visibility: hidden;
          backface-visibility: hidden; }

// Activate class
.slideIn-mui-enter.slideIn-mui-enter-active {
  -webkit-transform: translateY(0);
      -ms-transform: translateY(0);
          transform: translateY(0); }
```

I know this function really needs a test, but I can't write one because True (and Bootcamp as far as I know) nest your tests inside a CSS selector, which throws off the value of `&`. I might write some kind of manual test that prints out every permutation.

**Comment by HugoGiraudel** [comment]
Mpf...

**Comment by gakimball** [comment]
Since this PR has gotten stale I'm going to close it out. You're contributions to the library were killer, though, so we hope to see you around again soon :)

**Comment by HugoGiraudel** [comment]
I’ll come back to this eventually. :)

**Pull request closed without merging**
